### PR TITLE
fix DisableErrSkip() driver option (adds unit test)

### LINKED ISSUE #207: DisableErrSkip() not working as expected
Hello,
to avoid the `driver: skip fast-path; continue as if unimplemented` error being attached to spans, I added the `DisableErrSkip()` option to the `otelsql.Wrap()` call like this:

`otelsql.Wrap(d, otelsql.WithSystem("mysql"), otelsql.DisableErrSkip())`

However, this hasn't produced the result I expected, as the error was still added to the spans.
I _think_ that this is because `vendor/go.nhat.io/otelsql/driver.go` in `newConnConfig` does not add the `errorToSpanStatus` function to `t.errorToStatus` (`t` being `methodTracerImpl`).
I have patched the lib to add it, and it looks like it's working now (spans are not marked as error any longer, using the option). 
If you agree, I could provide a PR with that change.

Also, do you have any additional insights as to how I could circumvent the error to happen in the first place (using github.com/go-sql-driver/mysql v1.7.1 with MySQL v8)?

Thanks a lot!

### PR DESCRIPTION
**Pull request by pmlanger**
Fix #207 

It also adds a test. Let me know if it fits in well enough!

### CODE REVIEW

File: driver_test.go [hunk 1]
```diff
@@ -373,6 +373,36 @@ func Test_Ping_Error(t *testing.T) {
...
 
+func Test_ErrSkip_Error(t *testing.T) {
+	t.Parallel()
+
+	var skipErr = driver.ErrSkip
+
+	oteltest.New(
+		oteltest.MockDatabase(func(m sqlmock.Sqlmock) {
+			m.ExpectPing().
+				WillReturnError(skipErr)
```
Comment (nhatthm) [inline driver_test.go]: Can we just use `driver.ErrSkip` directly?

Comment (pmlanger) [reply driver_test.go]: Done ✅

**Comment by nhatthm** [comment]
@pmlanger Awesome, thanks for the tests 👍
